/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test_alumni_202457201055;

/**
 *
 * @author Nabila
 */
public class panelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public panelDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pUtama = new javax.swing.JPanel();
        pDashboard = new javax.swing.JPanel();
        lDashboard = new javax.swing.JLabel();
        bClose = new javax.swing.JButton();
        pJurusan = new javax.swing.JPanel();
        pJumlahJurusan = new javax.swing.JPanel();
        lJumlahJurusan = new javax.swing.JLabel();
        lTotalJurusan = new javax.swing.JLabel();
        pGuru = new javax.swing.JPanel();
        pJumlahGuru = new javax.swing.JPanel();
        lJumlahGuru = new javax.swing.JLabel();
        lTotalGuru = new javax.swing.JLabel();
        pSiswa = new javax.swing.JPanel();
        pJumlahSiswa = new javax.swing.JPanel();
        lJumlahSiswa = new javax.swing.JLabel();
        lTotalSiswa = new javax.swing.JLabel();
        pKelas = new javax.swing.JPanel();
        pJumlahKelas = new javax.swing.JPanel();
        lJumlahKelas = new javax.swing.JLabel();
        lTotalKelas = new javax.swing.JLabel();

        pUtama.setBackground(new java.awt.Color(204, 204, 204));
        pUtama.setDoubleBuffered(false);
        pUtama.setFocusCycleRoot(true);
        pUtama.setPreferredSize(new java.awt.Dimension(947, 653));

        pDashboard.setBackground(new java.awt.Color(255, 204, 204));

        lDashboard.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lDashboard.setText("DASHBOARD");

        bClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-close-30.png"))); // NOI18N
        bClose.setBorder(null);
        bClose.setContentAreaFilled(false);
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDashboardLayout = new javax.swing.GroupLayout(pDashboard);
        pDashboard.setLayout(pDashboardLayout);
        pDashboardLayout.setHorizontalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bClose)
                .addGap(14, 14, 14))
        );
        pDashboardLayout.setVerticalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bClose)
                    .addComponent(lDashboard))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pJumlahJurusan.setBackground(new java.awt.Color(255, 204, 204));

        lJumlahJurusan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lJumlahJurusan.setText("Jumlah Jurusan");

        javax.swing.GroupLayout pJumlahJurusanLayout = new javax.swing.GroupLayout(pJumlahJurusan);
        pJumlahJurusan.setLayout(pJumlahJurusanLayout);
        pJumlahJurusanLayout.setHorizontalGroup(
            pJumlahJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJumlahJurusanLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lJumlahJurusan)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pJumlahJurusanLayout.setVerticalGroup(
            pJumlahJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJumlahJurusanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lJumlahJurusan)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lTotalJurusan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lTotalJurusan.setText("3");

        javax.swing.GroupLayout pJurusanLayout = new javax.swing.GroupLayout(pJurusan);
        pJurusan.setLayout(pJurusanLayout);
        pJurusanLayout.setHorizontalGroup(
            pJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pJumlahJurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pJurusanLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lTotalJurusan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pJurusanLayout.setVerticalGroup(
            pJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJurusanLayout.createSequentialGroup()
                .addComponent(pJumlahJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lTotalJurusan)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pJumlahGuru.setBackground(new java.awt.Color(255, 204, 204));

        lJumlahGuru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lJumlahGuru.setText("Jumlah Guru");

        javax.swing.GroupLayout pJumlahGuruLayout = new javax.swing.GroupLayout(pJumlahGuru);
        pJumlahGuru.setLayout(pJumlahGuruLayout);
        pJumlahGuruLayout.setHorizontalGroup(
            pJumlahGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJumlahGuruLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lJumlahGuru)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pJumlahGuruLayout.setVerticalGroup(
            pJumlahGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJumlahGuruLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lJumlahGuru)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lTotalGuru.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lTotalGuru.setText("15");

        javax.swing.GroupLayout pGuruLayout = new javax.swing.GroupLayout(pGuru);
        pGuru.setLayout(pGuruLayout);
        pGuruLayout.setHorizontalGroup(
            pGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pJumlahGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pGuruLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lTotalGuru)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pGuruLayout.setVerticalGroup(
            pGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGuruLayout.createSequentialGroup()
                .addComponent(pJumlahGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lTotalGuru)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pJumlahSiswa.setBackground(new java.awt.Color(255, 204, 204));

        lJumlahSiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lJumlahSiswa.setText("Jumlah Siswa");

        javax.swing.GroupLayout pJumlahSiswaLayout = new javax.swing.GroupLayout(pJumlahSiswa);
        pJumlahSiswa.setLayout(pJumlahSiswaLayout);
        pJumlahSiswaLayout.setHorizontalGroup(
            pJumlahSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJumlahSiswaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lJumlahSiswa)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pJumlahSiswaLayout.setVerticalGroup(
            pJumlahSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJumlahSiswaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lJumlahSiswa)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lTotalSiswa.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lTotalSiswa.setText("300");

        javax.swing.GroupLayout pSiswaLayout = new javax.swing.GroupLayout(pSiswa);
        pSiswa.setLayout(pSiswaLayout);
        pSiswaLayout.setHorizontalGroup(
            pSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pJumlahSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pSiswaLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lTotalSiswa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pSiswaLayout.setVerticalGroup(
            pSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSiswaLayout.createSequentialGroup()
                .addComponent(pJumlahSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lTotalSiswa)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pJumlahKelas.setBackground(new java.awt.Color(255, 204, 204));

        lJumlahKelas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lJumlahKelas.setText("Jumlah Kelas");

        javax.swing.GroupLayout pJumlahKelasLayout = new javax.swing.GroupLayout(pJumlahKelas);
        pJumlahKelas.setLayout(pJumlahKelasLayout);
        pJumlahKelasLayout.setHorizontalGroup(
            pJumlahKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJumlahKelasLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lJumlahKelas)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pJumlahKelasLayout.setVerticalGroup(
            pJumlahKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJumlahKelasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lJumlahKelas)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lTotalKelas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lTotalKelas.setText("10");

        javax.swing.GroupLayout pKelasLayout = new javax.swing.GroupLayout(pKelas);
        pKelas.setLayout(pKelasLayout);
        pKelasLayout.setHorizontalGroup(
            pKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pJumlahKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pKelasLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lTotalKelas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pKelasLayout.setVerticalGroup(
            pKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKelasLayout.createSequentialGroup()
                .addComponent(pJumlahKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lTotalKelas)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pUtamaLayout = new javax.swing.GroupLayout(pUtama);
        pUtama.setLayout(pUtamaLayout);
        pUtamaLayout.setHorizontalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUtamaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(pJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(pGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(pSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(pKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addComponent(pDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pUtamaLayout.setVerticalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUtamaLayout.createSequentialGroup()
                .addComponent(pDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        // TODO add your handling code here:
        pUtama.setVisible(false);
    }//GEN-LAST:event_bCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JLabel lDashboard;
    private javax.swing.JLabel lJumlahGuru;
    private javax.swing.JLabel lJumlahJurusan;
    private javax.swing.JLabel lJumlahKelas;
    private javax.swing.JLabel lJumlahSiswa;
    private javax.swing.JLabel lTotalGuru;
    private javax.swing.JLabel lTotalJurusan;
    private javax.swing.JLabel lTotalKelas;
    private javax.swing.JLabel lTotalSiswa;
    private javax.swing.JPanel pDashboard;
    private javax.swing.JPanel pGuru;
    private javax.swing.JPanel pJumlahGuru;
    private javax.swing.JPanel pJumlahJurusan;
    private javax.swing.JPanel pJumlahKelas;
    private javax.swing.JPanel pJumlahSiswa;
    private javax.swing.JPanel pJurusan;
    private javax.swing.JPanel pKelas;
    private javax.swing.JPanel pSiswa;
    private javax.swing.JPanel pUtama;
    // End of variables declaration//GEN-END:variables
}
