/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test_alumni_202457201055;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Nabila
 */
public class panelGuru extends javax.swing.JPanel {

    /**
     * Creates new form panelGuru
     */
    public panelGuru() {
        initComponents();
        reset();
        load_table_guru();
    }
    void reset(){
    
    tNIP.setText(null);
    tNIP.setEditable(true);
    tNama.setText(null);
    cbJenisKelamin.setSelectedItem(null);
    tAlamat.setText(null);
    }
    void load_table_guru() {
        DefaultTableModel model = new DefaultTableModel();
            model.addColumn("NIP");
            model.addColumn("Nama Guru");
            model.addColumn("Alamat");

        String sql = "SELECT * FROM guru";
        try {
            Connection conn = koneksi.connect();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
            String NIP = rs.getString("nip");
            String Nama = rs.getString("nama_guru");
            String jenisKelamin = rs.getString("gender");
            String alamat = rs.getString("alamat");
            
            Object[] baris = {NIP, Nama, jenisKelamin, alamat};
            model.addRow(baris);

            }
            
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Gagal memilih data!");
        }
            tbGuru.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pUtama = new javax.swing.JPanel();
        pDataGuru = new javax.swing.JPanel();
        lDataGuru = new javax.swing.JLabel();
        bClose = new javax.swing.JButton();
        lAlamat = new javax.swing.JLabel();
        tNIP = new javax.swing.JTextField();
        lNIP = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        lNama = new javax.swing.JLabel();
        cbJenisKelamin = new javax.swing.JComboBox<>();
        lJenisKelamin = new javax.swing.JLabel();
        tAlamat = new javax.swing.JTextField();
        bReset = new javax.swing.JButton();
        bTambah1 = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGuru = new javax.swing.JTable();

        pUtama.setBackground(new java.awt.Color(204, 204, 204));
        pUtama.setForeground(new java.awt.Color(255, 255, 255));
        pUtama.setPreferredSize(new java.awt.Dimension(947, 786));

        pDataGuru.setBackground(new java.awt.Color(255, 204, 204));
        pDataGuru.setPreferredSize(new java.awt.Dimension(177, 58));

        lDataGuru.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lDataGuru.setText(" Data Guru");

        bClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-close-30.png"))); // NOI18N
        bClose.setContentAreaFilled(false);
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDataGuruLayout = new javax.swing.GroupLayout(pDataGuru);
        pDataGuru.setLayout(pDataGuruLayout);
        pDataGuruLayout.setHorizontalGroup(
            pDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lDataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bClose)
                .addContainerGap())
        );
        pDataGuruLayout.setVerticalGroup(
            pDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataGuruLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDataGuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bClose)
                    .addComponent(lDataGuru))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lAlamat.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lAlamat.setText("Alamat");

        tNIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNIPActionPerformed(evt);
            }
        });

        lNIP.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lNIP.setText("NIP");

        tNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaActionPerformed(evt);
            }
        });

        lNama.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lNama.setText("Nama");

        cbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        cbJenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisKelaminActionPerformed(evt);
            }
        });

        lJenisKelamin.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lJenisKelamin.setText("Jenis Kelamin");

        tAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAlamatActionPerformed(evt);
            }
        });

        bReset.setBackground(new java.awt.Color(0, 153, 255));
        bReset.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-reset-20 (1).png"))); // NOI18N
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        bTambah1.setBackground(new java.awt.Color(0, 204, 0));
        bTambah1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bTambah1.setForeground(new java.awt.Color(255, 255, 255));
        bTambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-plus-20.png"))); // NOI18N
        bTambah1.setText("Tambah");
        bTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambah1ActionPerformed(evt);
            }
        });

        bHapus.setBackground(new java.awt.Color(255, 51, 0));
        bHapus.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-delete-20 (1).png"))); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bUbah.setBackground(new java.awt.Color(255, 153, 0));
        bUbah.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bUbah.setForeground(new java.awt.Color(255, 255, 255));
        bUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-edit-20.png"))); // NOI18N
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        tbGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGuruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbGuru);

        javax.swing.GroupLayout pUtamaLayout = new javax.swing.GroupLayout(pUtama);
        pUtama.setLayout(pUtamaLayout);
        pUtamaLayout.setHorizontalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pDataGuru, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
            .addGroup(pUtamaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tNIP)
                        .addComponent(lNIP)
                        .addComponent(lNama)
                        .addComponent(tNama)
                        .addComponent(lJenisKelamin)
                        .addComponent(cbJenisKelamin, 0, 284, Short.MAX_VALUE)
                        .addComponent(tAlamat))
                    .addComponent(lAlamat))
                .addGap(26, 26, 26)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addComponent(bTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pUtamaLayout.setVerticalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUtamaLayout.createSequentialGroup()
                .addComponent(pDataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addComponent(lNIP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lJenisKelamin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lAlamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        pUtama.setVisible(false);
    }//GEN-LAST:event_bCloseActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        reset();
    }//GEN-LAST:event_bResetActionPerformed

    private void bTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambah1ActionPerformed
        String NIP = tNIP.getText();
        String namaGuru = tNama.getText();
        String jenisKelamin = cbJenisKelamin.getSelectedItem().toString();
        String alamat = tAlamat.getText();
        String jK = null;
        
        switch(jenisKelamin){
            case "Laki-laki":
                jK = "L";
                break;
            case "Perempuan":
                jK = "P";
                break;
            default:
                jK = null;
                break;
        }
        String sql = "INSERT INTO guru(nip, nama_guru, gender, alamat) VALUES (?,?,?,?)";
        
        try {
        Connection conn = koneksi.connect();
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, NIP);
        ps.setString(2, namaGuru);
        ps.setString(3, jK);
        ps.setString(4, alamat);
        ps.execute();
        
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        }catch (SQLException sQLException){
        JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
        }
        load_table_guru();
        reset();
    }//GEN-LAST:event_bTambah1ActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        int row = tbGuru.getSelectedRow();
        if (row != -1) {
            DefaultTableModel model = (DefaultTableModel) tbGuru.getModel();
            model.setValueAt(tNIP.getText(), row, 0);
            model.setValueAt(tNama.getText(), row, 1);
            model.setValueAt(cbJenisKelamin.getSelectedItem().toString(), row, 2);
            model.setValueAt(tAlamat.getText(), row, 3);
        }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        String NIP = tNIP.getText();
        String sql = "DELETE FROM guru WHERE nip = ?";
        try {
        Connection conn = koneksi.connect();
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, NIP);
        ps.execute();
        JOptionPane.showMessageDialog(null, "Data Berhasil dihapus!");
        } catch(SQLException sQLException){
        JOptionPane.showMessageDialog(null, "Data Gagal dihapus!");
        }
        load_table_guru();
        reset();
    }//GEN-LAST:event_bHapusActionPerformed

    private void tNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNIPActionPerformed

    private void tNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaActionPerformed

    private void cbJenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisKelaminActionPerformed

    private void tAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAlamatActionPerformed

    private void tbGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGuruMouseClicked
        int barisYangDipilih = tbGuru.rowAtPoint(evt.getPoint());

        String NIP = tbGuru.getValueAt(barisYangDipilih, 0).toString();
        String namaGuru = tbGuru.getValueAt(barisYangDipilih, 1).toString();
        String jenisKelamin = tbGuru.getValueAt(barisYangDipilih, 2).toString();
        String alamat = tbGuru.getValueAt(barisYangDipilih, 3).toString();
        
        tNIP.setText(NIP);
        tNIP.setEditable(false);
        tNama.setText(namaGuru);
        tAlamat.setText(alamat);

        switch (jenisKelamin) {
            case "L":
                cbJenisKelamin.setSelectedItem("Laki-laki");
                break;
            case "P":
                cbJenisKelamin.setSelectedItem("Perempuan");
                break;
            default:
                cbJenisKelamin.setSelectedItem(null);
                throw new AssertionError();
        }
    }//GEN-LAST:event_tbGuruMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah1;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox<String> cbJenisKelamin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAlamat;
    private javax.swing.JLabel lDataGuru;
    private javax.swing.JLabel lJenisKelamin;
    private javax.swing.JLabel lNIP;
    private javax.swing.JLabel lNama;
    private javax.swing.JPanel pDataGuru;
    private javax.swing.JPanel pUtama;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tNIP;
    private javax.swing.JTextField tNama;
    private javax.swing.JTable tbGuru;
    // End of variables declaration//GEN-END:variables

}
