/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test_alumni_202457201055;

/**
 *
 * @author Nabila
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class panelKelas extends javax.swing.JPanel {

    /**
     * Creates new form panelKelas
     */
    public panelKelas() {
        initComponents();
        reset();
        load_table_kelas();
        comboJurusan();
        comboWali();
    }
void reset() {
        tKodeKelas.setText(null);
        tKodeKelas.setEditable(true);
        tNamaKelas.setText(null);
        cbTingkatan.setSelectedItem(null);
        cbJurusan.setSelectedItem(null);
        cbWaliKelas.setSelectedItem(null);
    }

    void load_table_kelas() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Kelas");
        model.addColumn("Nama Kelas");
        model.addColumn("Tingkatan");
        model.addColumn("Jurusan");
        model.addColumn("Wali Kelas");

        String sql = "SELECT k.id_kelas, k.nama_kelas, k.tingkatan, j.nama_jurusan, g.nama_guru "
                   + "FROM kelas k "
                   + "LEFT JOIN jurusan j ON k.kode_jur = j.kode_jur "
                   + "LEFT JOIN guru g ON k.nip_Wali_kelas = g.nip";
        try {
            Connection conn = koneksi.connect();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String kodeKelas = rs.getString("id_kelas");
                String namaKelas = rs.getString("nama_kelas");
                String tingkatan = rs.getString("tingkatan");
                String jurusan = rs.getString("nama_jurusan");
                String waliKelas = rs.getString("nama_guru");

                Object[] baris = {kodeKelas, namaKelas, tingkatan, jurusan, waliKelas};
                model.addRow(baris);
            }
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil data!\n" + sQLException.getMessage());
        }

        tbDataKelas.setModel(model);
    }

    void comboJurusan() {
        try {
            String sql = "SELECT * FROM jurusan";
            Connection conn = koneksi.connect();
            Statement statement = conn.createStatement();
            ResultSet resultSet = statement.executeQuery(sql);

            while (resultSet.next()) {
                cbJurusan.addItem(resultSet.getString("nama_jurusan"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data jurusan\n" + e.getMessage());
        }
        cbJurusan.setSelectedItem(null);
    }

    void comboWali() {
        try {
            String sql = "SELECT * FROM guru";
            Connection conn = koneksi.connect();
            Statement statement = conn.createStatement();
            ResultSet resultSet = statement.executeQuery(sql);

            while (resultSet.next()) {
                cbWaliKelas.addItem(resultSet.getString("nama_guru"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data wali kelas\n" + e.getMessage());
        }
        cbWaliKelas.setSelectedItem(null);
    }

    String KodeJurusan(String NamaJurusan) {
        try {
            String sql = "SELECT * FROM jurusan WHERE nama_jurusan = ?";
            Connection conn = koneksi.connect();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, NamaJurusan);
            ResultSet resultSet = ps.executeQuery();
            if (resultSet.next()) {
                return resultSet.getString("kode_jur");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil kode jurusan\n" + e.getMessage());
        }
        return "";
    }

    String NIP(String NamaGuru) {
        try {
            String sql = "SELECT * FROM guru WHERE nama_guru = ?";
            Connection conn = koneksi.connect();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, NamaGuru);
            ResultSet resultSet = ps.executeQuery();
            if (resultSet.next()) {
                return resultSet.getString("nip");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil NIP\n" + e.getMessage());
        }
        return "";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pUtama = new javax.swing.JPanel();
        pDataKelas = new javax.swing.JPanel();
        lDataKelas = new javax.swing.JLabel();
        bClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDataKelas = new javax.swing.JTable();
        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        lKodeKelas = new javax.swing.JLabel();
        lNamaKelas = new javax.swing.JLabel();
        lTingkatan = new javax.swing.JLabel();
        lJurusan = new javax.swing.JLabel();
        lWaliKelas = new javax.swing.JLabel();
        tKodeKelas = new javax.swing.JTextField();
        tNamaKelas = new javax.swing.JTextField();
        cbTingkatan = new javax.swing.JComboBox<>();
        cbJurusan = new javax.swing.JComboBox<>();
        cbWaliKelas = new javax.swing.JComboBox<>();

        pUtama.setBackground(new java.awt.Color(204, 204, 204));
        pUtama.setPreferredSize(new java.awt.Dimension(874, 516));

        pDataKelas.setBackground(new java.awt.Color(255, 204, 204));
        pDataKelas.setPreferredSize(new java.awt.Dimension(177, 58));

        lDataKelas.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lDataKelas.setText("Data Kelas");

        bClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-close-30.png"))); // NOI18N
        bClose.setContentAreaFilled(false);

        javax.swing.GroupLayout pDataKelasLayout = new javax.swing.GroupLayout(pDataKelas);
        pDataKelas.setLayout(pDataKelasLayout);
        pDataKelasLayout.setHorizontalGroup(
            pDataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataKelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lDataKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bClose)
                .addContainerGap())
        );
        pDataKelasLayout.setVerticalGroup(
            pDataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataKelasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bClose)
                    .addComponent(lDataKelas))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tbDataKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDataKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataKelasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDataKelas);

        bTambah.setBackground(new java.awt.Color(0, 204, 0));
        bTambah.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bTambah.setForeground(new java.awt.Color(255, 255, 255));
        bTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-plus-20.png"))); // NOI18N
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bUbah.setBackground(new java.awt.Color(255, 153, 0));
        bUbah.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bUbah.setForeground(new java.awt.Color(255, 255, 255));
        bUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-edit-20.png"))); // NOI18N
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bHapus.setBackground(new java.awt.Color(255, 51, 0));
        bHapus.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-delete-20 (1).png"))); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bReset.setBackground(new java.awt.Color(0, 153, 255));
        bReset.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-reset-20 (1).png"))); // NOI18N
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        lKodeKelas.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lKodeKelas.setText("Kode Kelas");

        lNamaKelas.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lNamaKelas.setText("Nama Kelas");

        lTingkatan.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lTingkatan.setText("Tingkatan");

        lJurusan.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lJurusan.setText("Jurusan");

        lWaliKelas.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lWaliKelas.setText("Wali Kelas");

        tNamaKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        cbTingkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12" }));

        cbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IPA", "IPS" }));

        cbWaliKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rauhatun", "Arma" }));

        javax.swing.GroupLayout pUtamaLayout = new javax.swing.GroupLayout(pUtama);
        pUtama.setLayout(pUtamaLayout);
        pUtamaLayout.setHorizontalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pDataKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUtamaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lJurusan)
                    .addComponent(lKodeKelas)
                    .addComponent(lNamaKelas)
                    .addComponent(lTingkatan)
                    .addComponent(lWaliKelas)
                    .addComponent(cbJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTingkatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tNamaKelas)
                    .addComponent(tKodeKelas)
                    .addComponent(cbWaliKelas, 0, 328, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pUtamaLayout.setVerticalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUtamaLayout.createSequentialGroup()
                .addComponent(pDataKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addComponent(lKodeKelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tKodeKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lNamaKelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNamaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lTingkatan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTingkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lWaliKelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pUtama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        String KodeKelas = tKodeKelas.getText();
        String NamaKelas = tNamaKelas.getText();
        String Tingkatan = cbTingkatan.getSelectedItem().toString();
        String Jurusan = KodeJurusan(cbJurusan.getSelectedItem().toString());
        String WaliKelas = NIP(cbWaliKelas.getSelectedItem().toString());
        
        try{
        String sql = "UPDATE kelas SET nama_kelas=?, tingkatan=?, kode_jur?, nip_wali_kelas=? WHERE id_kelas=?";
        
            Connection conn = koneksi.connect();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, KodeKelas);
            ps.setString(2, NamaKelas);
            ps.setString(3, Tingkatan);
            ps.setString(4, Jurusan);
            ps.setString(5, WaliKelas);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
        } catch (SQLException sQLException) {
        JOptionPane.showMessageDialog(null, "Data gagal diubah!!!");
        }
        load_table_kelas();
        reset();
    }//GEN-LAST:event_bUbahActionPerformed

    private void tbDataKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataKelasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDataKelasMouseClicked

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        String KodeKelas = tKodeKelas.getText();
        String NamaKelas = tNamaKelas.getText();
        String Tingkatan = cbTingkatan.getSelectedItem().toString();
        String Jurusan = KodeJurusan(cbJurusan.getSelectedItem().toString());
        String WaliKelas = NIP(cbWaliKelas.getSelectedItem().toString());
        
        try{
        String sql = "INSERT INTO kelas (id_kelas, nama_kelas, tingkatan, kode_jur, nip, wali_kelas) VALUES (?,?,?,?,?,?)";
        
            Connection conn = koneksi.connect();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, KodeKelas);
            ps.setString(2, NamaKelas);
            ps.setString(3, Tingkatan);
            ps.setString(4, Jurusan);
            ps.setString(5, WaliKelas);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!");
        } catch (SQLException sQLException) {
        JOptionPane.showMessageDialog(null, "Data Gagal Disimpan!!!");
        }
        load_table_kelas();
        reset();
    }//GEN-LAST:event_bTambahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        String KodeKelas = tKodeKelas.getText();
        try{
            String sql = "DELETE FROM kelas WHERE id_kelas=?";
            Connection conn = koneksi.connect();
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, KodeKelas);
            statement.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        } catch (SQLException e){
        JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
        }
        load_table_kelas();
        reset();
    }//GEN-LAST:event_bHapusActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        reset();
    }//GEN-LAST:event_bResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox<String> cbJurusan;
    private javax.swing.JComboBox<String> cbTingkatan;
    private javax.swing.JComboBox<String> cbWaliKelas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lDataKelas;
    private javax.swing.JLabel lJurusan;
    private javax.swing.JLabel lKodeKelas;
    private javax.swing.JLabel lNamaKelas;
    private javax.swing.JLabel lTingkatan;
    private javax.swing.JLabel lWaliKelas;
    private javax.swing.JPanel pDataKelas;
    private javax.swing.JPanel pUtama;
    private javax.swing.JTextField tKodeKelas;
    private javax.swing.JTextField tNamaKelas;
    private javax.swing.JTable tbDataKelas;
    // End of variables declaration//GEN-END:variables
}
