/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test_alumni_202457201055;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nabila
 */
public class panelSiswa extends javax.swing.JPanel {

    /**
     * Creates new form panelSiswa
     */
    DefaultTableModel model;

    public panelSiswa() {
        initComponents();
        String[] kolom = {"NIS", "Nama", "Jenis Kelamin", "Tempat Lahir", "Tanggal Lahir", "No HP", "Kelas", "Alamat"};
        model = new DefaultTableModel(null, kolom);
        tbDataSsiwa.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pUtama = new javax.swing.JPanel();
        pDataSiswa = new javax.swing.JPanel();
        lDataSiswa = new javax.swing.JLabel();
        bClose = new javax.swing.JButton();
        pFoto = new javax.swing.JPanel();
        lFoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDataSsiwa = new javax.swing.JTable();
        lNIS = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();
        lJenisKelamin = new javax.swing.JLabel();
        lTempatLahir = new javax.swing.JLabel();
        lTanggalLahir = new javax.swing.JLabel();
        tNIS = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        tTempatLahir = new javax.swing.JTextField();
        tTanggalLahir = new javax.swing.JTextField();
        cbJenisKelamin = new javax.swing.JComboBox<>();
        lNomorHP = new javax.swing.JLabel();
        lKelas = new javax.swing.JLabel();
        lAlamat = new javax.swing.JLabel();
        tNomorHP = new javax.swing.JTextField();
        tAlamat = new javax.swing.JTextField();
        cbKelas = new javax.swing.JComboBox<>();
        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();

        pUtama.setBackground(new java.awt.Color(204, 204, 204));

        pDataSiswa.setBackground(new java.awt.Color(255, 204, 204));
        pDataSiswa.setPreferredSize(new java.awt.Dimension(177, 58));

        lDataSiswa.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lDataSiswa.setText("Data Siswa");

        bClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-close-30.png"))); // NOI18N
        bClose.setContentAreaFilled(false);
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDataSiswaLayout = new javax.swing.GroupLayout(pDataSiswa);
        pDataSiswa.setLayout(pDataSiswaLayout);
        pDataSiswaLayout.setHorizontalGroup(
            pDataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataSiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lDataSiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bClose)
                .addGap(35, 35, 35))
        );
        pDataSiswaLayout.setVerticalGroup(
            pDataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataSiswaLayout.createSequentialGroup()
                .addGroup(pDataSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDataSiswaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lDataSiswa))
                    .addGroup(pDataSiswaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bClose)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lFoto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lFoto.setText("Foto");

        javax.swing.GroupLayout pFotoLayout = new javax.swing.GroupLayout(pFoto);
        pFoto.setLayout(pFotoLayout);
        pFotoLayout.setHorizontalGroup(
            pFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFotoLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(lFoto)
                .addGap(88, 88, 88))
        );
        pFotoLayout.setVerticalGroup(
            pFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFotoLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lFoto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbDataSsiwa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbDataSsiwa);

        lNIS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lNIS.setText("NIS");

        lNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lNama.setText("Nama");

        lJenisKelamin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lJenisKelamin.setText("Jenis Kelamin");

        lTempatLahir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTempatLahir.setText("Tempat Lahir");

        lTanggalLahir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTanggalLahir.setText("Tanggal Lahir");

        tNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNISActionPerformed(evt);
            }
        });

        tNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaActionPerformed(evt);
            }
        });

        tTempatLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTempatLahirActionPerformed(evt);
            }
        });

        tTanggalLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTanggalLahirActionPerformed(evt);
            }
        });

        cbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        cbJenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisKelaminActionPerformed(evt);
            }
        });

        lNomorHP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lNomorHP.setText("Nomor Hp");

        lKelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lKelas.setText("Kelas");

        lAlamat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lAlamat.setText("Alamat");

        tNomorHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNomorHPActionPerformed(evt);
            }
        });

        tAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAlamatActionPerformed(evt);
            }
        });

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12" }));
        cbKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKelasActionPerformed(evt);
            }
        });

        bTambah.setBackground(new java.awt.Color(0, 204, 0));
        bTambah.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bTambah.setForeground(new java.awt.Color(255, 255, 255));
        bTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-plus-20.png"))); // NOI18N
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bUbah.setBackground(new java.awt.Color(255, 153, 0));
        bUbah.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bUbah.setForeground(new java.awt.Color(255, 255, 255));
        bUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-edit-20.png"))); // NOI18N
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bHapus.setBackground(new java.awt.Color(255, 51, 0));
        bHapus.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-delete-20 (1).png"))); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bReset.setBackground(new java.awt.Color(0, 153, 255));
        bReset.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-reset-20 (1).png"))); // NOI18N
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pUtamaLayout = new javax.swing.GroupLayout(pUtama);
        pUtama.setLayout(pUtamaLayout);
        pUtamaLayout.setHorizontalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pDataSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
            .addGroup(pUtamaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(394, 394, 394))
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pUtamaLayout.createSequentialGroup()
                                .addComponent(pFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNIS)
                                    .addComponent(tNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lNama)
                                    .addComponent(lJenisKelamin)
                                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lTempatLahir)
                                    .addComponent(tTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lTanggalLahir))
                                .addGap(18, 18, 18)
                                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lAlamat, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lKelas, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNomorHP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbKelas, javax.swing.GroupLayout.Alignment.LEADING, 0, 281, Short.MAX_VALUE)
                                    .addComponent(tAlamat, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tNomorHP, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pUtamaLayout.setVerticalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUtamaLayout.createSequentialGroup()
                .addComponent(pDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNIS)
                            .addComponent(lNomorHP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tNomorHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNama)
                            .addComponent(lKelas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lJenisKelamin)
                            .addComponent(lAlamat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pUtamaLayout.createSequentialGroup()
                                .addComponent(cbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lTempatLahir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lTanggalLahir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tAlamat)))
                    .addComponent(pFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNISActionPerformed

    private void tNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaActionPerformed

    private void tTempatLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTempatLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTempatLahirActionPerformed

    private void tTanggalLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTanggalLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTanggalLahirActionPerformed

    private void tNomorHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNomorHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNomorHPActionPerformed

    private void tAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAlamatActionPerformed

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
      pUtama.setVisible(false);
    }//GEN-LAST:event_bCloseActionPerformed

    private void cbJenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisKelaminActionPerformed

    private void cbKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKelasActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
           String nis = tNIS.getText();
        String nama = tNama.getText();
        String jk = cbJenisKelamin.getSelectedItem().toString();
        String tempat = tTempatLahir.getText();
        String tanggal = tTanggalLahir.getText();
        String hp = tNomorHP.getText();
        String kelas = cbKelas.getSelectedItem().toString();
        String alamat = tAlamat.getText();

        if (!nis.isEmpty() && !nama.isEmpty() && !tempat.isEmpty() && !tanggal.isEmpty() && !hp.isEmpty() && !alamat.isEmpty()) {
            String[] data = {nis, nama, jk, tempat, tanggal, hp, kelas, alamat};
            model.addRow(data);
            tNIS.setText("");
            tNama.setText("");
            tTempatLahir.setText("");
            tTanggalLahir.setText("");
            tNomorHP.setText("");
            tAlamat.setText("");
            cbJenisKelamin.setSelectedIndex(0);
            cbKelas.setSelectedIndex(0);
        }
    }//GEN-LAST:event_bTambahActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        int row = tbDataSsiwa.getSelectedRow();
        if (row >= 0) {
            tbDataSsiwa.setValueAt(tNIS.getText(), row, 0);
            tbDataSsiwa.setValueAt(tNama.getText(), row, 1);
            tbDataSsiwa.setValueAt(cbJenisKelamin.getSelectedItem(), row, 2);
            tbDataSsiwa.setValueAt(tTempatLahir.getText(), row, 3);
            tbDataSsiwa.setValueAt(tTanggalLahir.getText(), row, 4);
            tbDataSsiwa.setValueAt(tNomorHP.getText(), row, 5);
            tbDataSsiwa.setValueAt(cbKelas.getSelectedItem(), row, 6);
            tbDataSsiwa.setValueAt(tAlamat.getText(), row, 7);
            tNIS.setText("");
            tNama.setText("");
            tTempatLahir.setText("");
            tTanggalLahir.setText("");
            tNomorHP.setText("");
            tAlamat.setText("");
            cbJenisKelamin.setSelectedIndex(0);
            cbKelas.setSelectedIndex(0);
        }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        int row = tbDataSsiwa.getSelectedRow();
        if (row >= 0) {
            model.removeRow(row);
            tNIS.setText("");
            tNama.setText("");
            tTempatLahir.setText("");
            tTanggalLahir.setText("");
            tNomorHP.setText("");
            tAlamat.setText("");
            cbJenisKelamin.setSelectedIndex(0);
            cbKelas.setSelectedIndex(0);
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        tNIS.setText("");
        tNama.setText("");
        tTempatLahir.setText("");
        tTanggalLahir.setText("");
        tNomorHP.setText("");
        tAlamat.setText("");
        cbJenisKelamin.setSelectedIndex(0);
        cbKelas.setSelectedIndex(0);
        tbDataSsiwa.clearSelection();
    }//GEN-LAST:event_bResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox<String> cbJenisKelamin;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAlamat;
    private javax.swing.JLabel lDataSiswa;
    private javax.swing.JLabel lFoto;
    private javax.swing.JLabel lJenisKelamin;
    private javax.swing.JLabel lKelas;
    private javax.swing.JLabel lNIS;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lNomorHP;
    private javax.swing.JLabel lTanggalLahir;
    private javax.swing.JLabel lTempatLahir;
    private javax.swing.JPanel pDataSiswa;
    private javax.swing.JPanel pFoto;
    private javax.swing.JPanel pUtama;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tNIS;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNomorHP;
    private javax.swing.JTextField tTanggalLahir;
    private javax.swing.JTextField tTempatLahir;
    private javax.swing.JTable tbDataSsiwa;
    // End of variables declaration//GEN-END:variables
}
