/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test_alumni_202457201055;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Nabila
 */
public class panelKelas extends javax.swing.JPanel {

    /**
     * Creates new form panelKelas
     */
    public panelKelas() {
        initComponents();
        tbDataKelas.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{"Kode Kelas", "Nama Kelas", "Tingkatan", "Jurusan", "Wali Kelas"}
    ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pUtama = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDataKelas = new javax.swing.JTable();
        pDataKelas = new javax.swing.JPanel();
        lDataKelas = new javax.swing.JLabel();
        bClose = new javax.swing.JButton();
        lKodeKelas = new javax.swing.JLabel();
        lNamaKelas = new javax.swing.JLabel();
        lTingkatan = new javax.swing.JLabel();
        lJurusan = new javax.swing.JLabel();
        lWaliKela = new javax.swing.JLabel();
        tKodeKelas = new javax.swing.JTextField();
        tNamaKelas = new javax.swing.JTextField();
        cbJurusan = new javax.swing.JComboBox<>();
        cbTingkatan = new javax.swing.JComboBox<>();
        cbWaliKelas = new javax.swing.JComboBox<>();
        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();

        pUtama.setBackground(new java.awt.Color(204, 204, 204));

        tbDataKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbDataKelas);

        pDataKelas.setBackground(new java.awt.Color(255, 204, 204));
        pDataKelas.setPreferredSize(new java.awt.Dimension(177, 58));

        lDataKelas.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lDataKelas.setText("Data Kelas");

        bClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-close-30.png"))); // NOI18N
        bClose.setToolTipText("");
        bClose.setContentAreaFilled(false);
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDataKelasLayout = new javax.swing.GroupLayout(pDataKelas);
        pDataKelas.setLayout(pDataKelasLayout);
        pDataKelasLayout.setHorizontalGroup(
            pDataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataKelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lDataKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bClose)
                .addContainerGap())
        );
        pDataKelasLayout.setVerticalGroup(
            pDataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataKelasLayout.createSequentialGroup()
                .addGroup(pDataKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDataKelasLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lDataKelas))
                    .addGroup(pDataKelasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bClose)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lKodeKelas.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lKodeKelas.setText("Kode Kelas");

        lNamaKelas.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lNamaKelas.setText("Nama Kelas");

        lTingkatan.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lTingkatan.setText("Tingkatan");

        lJurusan.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lJurusan.setText("Jurusan");

        lWaliKela.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lWaliKela.setText("Wali Kelas");

        tKodeKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKodeKelasActionPerformed(evt);
            }
        });

        tNamaKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaKelasActionPerformed(evt);
            }
        });

        cbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TKJ (Teknik Komputer dan Jaringan)", "RPL (Rekayasa Perangkat Lunak)", "MM (Multi Media)", "APHP (Agribisns Pengolahan Hasil Pertanian)" }));
        cbJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJurusanActionPerformed(evt);
            }
        });

        cbTingkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12" }));
        cbTingkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTingkatanActionPerformed(evt);
            }
        });

        cbWaliKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rauhatun Mubarokah", "You Arma Rusuli" }));
        cbWaliKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbWaliKelasActionPerformed(evt);
            }
        });

        bTambah.setBackground(new java.awt.Color(0, 204, 0));
        bTambah.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bTambah.setForeground(new java.awt.Color(255, 255, 255));
        bTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-plus-20.png"))); // NOI18N
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bUbah.setBackground(new java.awt.Color(255, 153, 0));
        bUbah.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bUbah.setForeground(new java.awt.Color(255, 255, 255));
        bUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-edit-20.png"))); // NOI18N
        bUbah.setText("Tambah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bHapus.setBackground(new java.awt.Color(255, 51, 0));
        bHapus.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-delete-20 (1).png"))); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bReset.setBackground(new java.awt.Color(0, 153, 255));
        bReset.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-reset-20 (1).png"))); // NOI18N
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pUtamaLayout = new javax.swing.GroupLayout(pUtama);
        pUtama.setLayout(pUtamaLayout);
        pUtamaLayout.setHorizontalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pDataKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUtamaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbWaliKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tNamaKelas)
                    .addComponent(cbTingkatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lKodeKelas)
                            .addComponent(lNamaKelas)
                            .addComponent(lTingkatan)
                            .addComponent(lJurusan)
                            .addComponent(lWaliKela)
                            .addComponent(tKodeKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        pUtamaLayout.setVerticalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUtamaLayout.createSequentialGroup()
                .addComponent(pDataKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addComponent(lKodeKelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tKodeKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lNamaKelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNamaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lTingkatan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTingkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lJurusan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lWaliKela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbTingkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTingkatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTingkatanActionPerformed

    private void cbWaliKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbWaliKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbWaliKelasActionPerformed

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        pUtama.setVisible(false);
    }//GEN-LAST:event_bCloseActionPerformed

    private void tKodeKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKodeKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tKodeKelasActionPerformed

    private void tNamaKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaKelasActionPerformed

    private void cbJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJurusanActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
         String kode = tKodeKelas.getText();
    String nama = tNamaKelas.getText();
    String tingkatan = cbTingkatan.getSelectedItem().toString();
    String jurusan = cbJurusan.getSelectedItem().toString();
    String wali = cbWaliKelas.getSelectedItem().toString();

    javax.swing.table.DefaultTableModel model = 
        (javax.swing.table.DefaultTableModel) tbDataKelas.getModel();

    model.addRow(new Object[]{kode, nama, tingkatan, jurusan, wali});
    }//GEN-LAST:event_bTambahActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        int row = tbDataKelas.getSelectedRow();
    if (row != -1) {
        javax.swing.table.DefaultTableModel model = 
            (javax.swing.table.DefaultTableModel) tbDataKelas.getModel();

        model.setValueAt(tKodeKelas.getText(), row, 0);
        model.setValueAt(tNamaKelas.getText(), row, 1);
        model.setValueAt(cbTingkatan.getSelectedItem().toString(), row, 2);
        model.setValueAt(cbJurusan.getSelectedItem().toString(), row, 3);
        model.setValueAt(cbWaliKelas.getSelectedItem().toString(), row, 4);
    }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        int row = tbDataKelas.getSelectedRow();
    if (row != -1) {
        javax.swing.table.DefaultTableModel model = 
            (javax.swing.table.DefaultTableModel) tbDataKelas.getModel();
        model.removeRow(row);
    }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
    tKodeKelas.setText("");
    tNamaKelas.setText("");
    cbTingkatan.setSelectedIndex(0);
    cbJurusan.setSelectedIndex(0);
    cbWaliKelas.setSelectedIndex(0);
    }//GEN-LAST:event_bResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox<String> cbJurusan;
    private javax.swing.JComboBox<String> cbTingkatan;
    private javax.swing.JComboBox<String> cbWaliKelas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lDataKelas;
    private javax.swing.JLabel lJurusan;
    private javax.swing.JLabel lKodeKelas;
    private javax.swing.JLabel lNamaKelas;
    private javax.swing.JLabel lTingkatan;
    private javax.swing.JLabel lWaliKela;
    private javax.swing.JPanel pDataKelas;
    private javax.swing.JPanel pUtama;
    private javax.swing.JTextField tKodeKelas;
    private javax.swing.JTextField tNamaKelas;
    private javax.swing.JTable tbDataKelas;
    // End of variables declaration//GEN-END:variables
}
