/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test_alumni_202457201055;

/**
 *
 * @author Nabila
 */
public class panelAbout extends javax.swing.JPanel {

    /**
     * Creates new form panelAbout
     */
    public panelAbout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pUtama = new javax.swing.JPanel();
        pAboutUs = new javax.swing.JPanel();
        lAboutUs = new javax.swing.JLabel();
        bClose = new javax.swing.JButton();
        lNama = new javax.swing.JLabel();
        lNIM = new javax.swing.JLabel();
        lProdi = new javax.swing.JLabel();
        lITM = new javax.swing.JLabel();

        pUtama.setBackground(new java.awt.Color(204, 204, 204));

        pAboutUs.setBackground(new java.awt.Color(255, 204, 204));
        pAboutUs.setPreferredSize(new java.awt.Dimension(177, 58));

        lAboutUs.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lAboutUs.setText("About Us");

        bClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test_alumni_202457201055/icons8-close-30.png"))); // NOI18N
        bClose.setContentAreaFilled(false);
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAboutUsLayout = new javax.swing.GroupLayout(pAboutUs);
        pAboutUs.setLayout(pAboutUsLayout);
        pAboutUsLayout.setHorizontalGroup(
            pAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAboutUsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lAboutUs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bClose)
                .addContainerGap())
        );
        pAboutUsLayout.setVerticalGroup(
            pAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAboutUsLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(pAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bClose)
                    .addComponent(lAboutUs))
                .addGap(14, 14, 14))
        );

        lNama.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lNama.setText("Aplikasi ini dibuat oleh Nabila Putri Ardina");

        lNIM.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lNIM.setText("NIM : 202457201055");

        lProdi.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lProdi.setText("Program Studi S1 Sistem Informasi");

        lITM.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lITM.setText("Institut Teknologi Mojosari");

        javax.swing.GroupLayout pUtamaLayout = new javax.swing.GroupLayout(pUtama);
        pUtama.setLayout(pUtamaLayout);
        pUtamaLayout.setHorizontalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pAboutUs, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(pUtamaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lITM)
                    .addComponent(lProdi)
                    .addComponent(lNIM)
                    .addComponent(lNama))
                .addContainerGap(418, Short.MAX_VALUE))
        );
        pUtamaLayout.setVerticalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUtamaLayout.createSequentialGroup()
                .addComponent(pAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lNIM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lProdi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lITM)
                .addGap(0, 356, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        pUtama.setVisible(false);
    }//GEN-LAST:event_bCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JLabel lAboutUs;
    private javax.swing.JLabel lITM;
    private javax.swing.JLabel lNIM;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lProdi;
    private javax.swing.JPanel pAboutUs;
    private javax.swing.JPanel pUtama;
    // End of variables declaration//GEN-END:variables
}
